

/usr/sbin/groupadd oae && useradd -r -m -s /bin/bash -g oae  oae

yum -y install wget  gcc-c++  unzip  pcre pcre-devel  zlib zlib-devel  openssl openssl-devel  git autoconf

mkdir -p /usr/local/webserver &&mkdir -p /data/software && cd /data/software

wget http://blog.zyan.cc/soft/linux/nginx_php/pcre/pcre-8.10.tar.gz &&tar zxvf pcre-8.10.tar.gz &&rm -f pcre-8.10.tar.gz &&cd pcre-8.10 &&./configure&& make&&make install && cd .. && \
wget http://tengine.taobao.org/download/tengine-2.1.2.tar.gz &&tar -zxvf tengine-2.1.2.tar.gz && rm -f tengine-2.1.2.tar.gz && cd tengine-2.1.2 && \
./configure --prefix=/usr/local/webserver/tengine  --user=oae --group=oae --with-http_stub_status_module --with-http_ssl_module --with-file-aio --with-http_realip_module  \
&& make &&make install



\cp nginx.conf  /usr/local/webserver/tengine/conf/nginx.conf

/usr/local/webserver/tengine/sbin/nginx -c conf/nginx.conf

\cp nginx /etc/init.d/nginx


#°²×°PHP
yum -y install  libxml2 libxml2-devel curl curl-devel libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel  && \
cd /data/software&&wget http://blog.zyan.cc/soft/linux/nginx_php/mcrypt/libmcrypt-2.5.8.tar.gz && tar zxvf libmcrypt-2.5.8.tar.gz &&rm -f libmcrypt-2.5.8.tar.gz && \
cd libmcrypt-2.5.8/ && ./configure --prefix=/usr/local && make && make install && rm -rf libmcrypt-2.5.8 && cd /data/software



cd /data/software && wget http://hk1.php.net/get/php-7.0.17.tar.gz/from/this/mirror &&tar zxvf mirror && rm -f mirror &&cd php-7.0.17 &&
./configure --prefix=/usr/local/webserver/php --with-config-file-path=/usr/local/webserver/php/etc --enable-fpm --with-fpm-user=oae --with-fpm-group=oae --with-mysqli --with-pdo-mysql --with-iconv-dir --with-freetype-dir --with-jpeg-dir --with-png-dir --with-zlib --with-libxml-dir=/usr --enable-xml --disable-rpath --enable-bcmath --enable-shmop --enable-sysvsem --enable-inline-optimization --with-curl --enable-mbregex --enable-mbstring  --enable-ftp --with-gd --enable-gd-native-ttf --with-openssl --with-mhash --enable-pcntl --enable-sockets --with-xmlrpc --enable-zip --enable-soap --without-pear --with-gettext --disable-fileinfo --enable-maintainer-zts && make && make install && \
cp ./php.ini-development /usr/local/webserver/php/etc/php.ini && \
sed -i '$aPATH=/usr/local/webserver/php/bin:\$PATH\n export PATH' /etc/profile  && source /etc/profile && \
mv /usr/local/webserver/php/etc/php-fpm.conf.default /usr/local/webserver/php/etc/php-fpm.conf && \
cp /data/software/php-7.0.17/sapi/fpm/init.d.php-fpm.in /etc/init.d/php-fpm && chmod 755 /etc/init.d/php-fpm && \
sed -i 's!@sbindir@!/usr/local/webserver/php/sbin!g'   /etc/init.d/php-fpm && \
sed -i 's!@sysconfdir@!/usr/local/webserver/php/etc!g'   /etc/init.d/php-fpm && \
sed -i 's!@localstatedir@!/usr/local/webserver/php!g'   /etc/init.d/php-fpm  && \
sed -i 's!127.0.0.1:9000!/var/run/php-fpm.sock!g'   /usr/local/webserver/php/etc/php-fpm.d/www.conf && \
/etc/init.d/php-fpm restart  && chown -R oae:oae /var/run/php-fpm.sock



cd /data/software && git clone https://github.com/phpredis/phpredis.git && cd phpredis/ && /usr/local/webserver/php/bin/phpize && ./configure --with-php-config=/usr/local/webserver/php/bin/php-config && make && make install  && \
sed -i '$a extension_dir =/usr/local/webserver/php/lib/php/extensions/no-debug-zts-20151012/\nextension  =redis.so\n' /usr/local/webserver/php/etc/php.ini 

cd /data/software &&wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz && tar zxvf libmemcached-1.0.18.tar.gz &&rm -f libmemcached-1.0.18.tar.gz &&cd libmemcached-1.0.18 &&\
mkdir -p /usr/local/webserver/libmemcached && \
./configure  --prefix=/usr/local/webserver/libmemcached&&make && make install && \
cd ../ && wget https://pecl.php.net/get/memcached-3.0.2.tgz &&tar zxvf memcached-3.0.2.tgz && rm -f memcached-3.0.2.tgz &&\
cd memcached-3.0.2 && /usr/local/webserver/php/bin/phpize && \
./configure --enable-memcached --with-php-config=/usr/local/webserver/php/bin/php-config --with-libmemcached-dir=/usr/local/webserver/libmemcached --disable-memcached-sasl &&\
make && make install && sed -i '$a extension =memcached.so\n' /usr/local/webserver/php/etc/php.ini && cd .. && rm -rf memcached-3.0.2 



//todo:next
cd /data/software && wget https://github.com/wcgallego/pecl-gearman/archive/master.zip && unzip master.zip && rm -f master.zip && \
cd pecl-gearman-master && /usr/local/webserver/php/bin/phpize && ./configure --prefix=/usr/local/webserver/gearman --with-php-config=/usr/local/webserver/php/bin/php-config && \
make && make install && sed -i '$a extension =gearman.so\n' /usr/local/webserver/php/etc/php.ini


#sed -i '$a extension =mongodb.so\n' /usr/local/webserver/php/etc/php.ini
#sed -i '$a extension =rdkafka.so\n' /usr/local/webserver/php/etc/php.ini
#sed -i '$a extension =xhprof.so\n' /usr/local/webserver/php/etc/php.ini
#sed -i '$a extension =xdebug.so\n' /usr/local/webserver/php/etc/php.ini
#sed -i '$a extension =opcache.so\n' /usr/local/webserver/php/etc/php.ini
#sed -i '$a extension =zmq.so\n' /usr/local/webserver/php/etc/php.ini















